# Generated by Django 3.2 on 2021-02-12 15:04

from django.db import migrations


def first_poll(apps, schema_editor):
    Question = apps.get_model('poll', 'Question')
    question = Question.objects.create(
        question_text='Did you successfully install the poll app?')
    question.choice_set.create(choice_text='Yes')
    question.choice_set.create(choice_text='No')


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(first_poll)
    ]
